### PR TITLE
Add Travis CI to the list of CI/CD providers

### PR DESCRIPTION
**Pull request by roidrage**
For reference: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/ and http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

Thank you for your consideration, and please let me know if I've missed anything or something's off! :heart:

### CODE REVIEW

**Comment by TylerJewell** [comment]
The comment needs to fit on two lines for the printed infographic.  How about, "Docker-based continuous integration and delivery"

**Comment by roidrage** [comment]
Sure thing, that works for me.

**Comment by TylerJewell** [comment]
Hi - thanks... but can you update the pull request with this change?  We need you to incorporate these comments into the PR so that we can make the merge and have it traceable back to your approval.  Thanks!

**Comment by roidrage** [comment]
Of course, my bad.

Done and done!

**Pull request merged**
